### ISSUE TITLE
Splitting strings into letters

### ISSUE THREAD

**Issue by karailiev** [smbape/node-ini-config-parser#1]
Hi,
I have following ini file:

```
db_user=someuser
db_pass=somepadd
db_name=mydatabase
```

and when I parse it, I get following result:

```
{ db_user:
   { '0': 's',
     '1': 'o',
     '2': 'm',
     '3': 'e',
     '4': 'u',
     '5': 's',
     '6': 'e',
     '7': 'r' },
  db_pass:
   { '0': 's',
     '1': 'o',
     '2': 'm',
     '3': 'e',
     '4': 'p',
     '5': 'a',
     '6': 'd',
     '7': 'd' },
  db_name:
   { '0': 'm',
     '1': 'y',
     '2': 'd',
     '3': 'a',
     '4': 't',
     '5': 'a',
     '6': 'b',
     '7': 'a',
     '8': 's',
     '9': 'e' } }
```

The problem does not exist if I use sections, but I prefer not to.
Am I doing something wrong?

**Comment by smbape** [comment]
Unfortunately global scope is not supported. I will mention it in the documention.
May I know the reason why you don't want to add an [undefined] scope?

**Comment by karailiev** [comment]
Thanks for the quick reply :)
The same ini file is used by other scripts, so I prefer to keep it as neutral as possible.
Making changes to suite one script would result in additional work in the rest.
However, I did some minor changes in the plugin and it seems to work fine with the global scope.
I'll do some tests and if all is good I'll do a pull request.

**Comment by smbape** [comment]
A new [version 1.0.0](https://github.com/smbape/node-ini-config-parser/tree/v1.0.0) as been released.
I hope the available options will sweet your needs.

Feel free to reopen an issue if not
